# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19VdSFxZ3WWvqDW36ECQU61bvv6TMZHWN
"""

!pip install flask pandas scikit-learn sentence-transformers datasets

from datasets import load_dataset
import pandas as pd

dataset = load_dataset("ag_news")

df = pd.DataFrame(dataset["train"])

# Combine title + description (important)
df["text"] = df["text"]

print(df.head())

from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

news_embeddings = model.encode(df["text"].tolist(), show_progress_bar=True)

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

def get_top_news(query, top_k=5):
    query_vec = model.encode([query])

    scores = cosine_similarity(query_vec, news_embeddings)[0]

    top_indices = np.argsort(scores)[-top_k:][::-1]

    results = df.iloc[top_indices][["text"]]

    return results.values.tolist()

query = "latest news in sports"
top_news_results = get_top_news(query, top_k=3)
print(f"Top 3 news articles for query: '{query}'")
for i, news_item in enumerate(top_news_results):
    print(f"Article {i+1}: {news_item[0]}")